// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/api/create-trip": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/all-users": {
    params: {};
  };
  "/trips": {
    params: {};
  };
  "/trips/create": {
    params: {};
  };
  "/trips/:tripId": {
    params: {
      "tripId": string;
    };
  };
  "/travel/:tripId": {
    params: {
      "tripId": string;
    };
  };
  "/travel/:tripId/success": {
    params: {
      "tripId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/api/create-trip" | "/dashboard" | "/all-users" | "/trips" | "/trips/create" | "/trips/:tripId" | "/travel/:tripId" | "/travel/:tripId/success";
  };
  "routes/root/sign-in.tsx": {
    id: "routes/root/sign-in";
    page: "/sign-in";
  };
  "routes/api/create-trip.ts": {
    id: "routes/api/create-trip";
    page: "/api/create-trip";
  };
  "routes/admin/admin-layout.tsx": {
    id: "routes/admin/admin-layout";
    page: "/dashboard" | "/all-users" | "/trips" | "/trips/create" | "/trips/:tripId";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/dashboard";
  };
  "routes/admin/all-users.tsx": {
    id: "routes/admin/all-users";
    page: "/all-users";
  };
  "routes/admin/trips.tsx": {
    id: "routes/admin/trips";
    page: "/trips";
  };
  "routes/admin/create-trip.tsx": {
    id: "routes/admin/create-trip";
    page: "/trips/create";
  };
  "routes/admin/trip-detail.tsx": {
    id: "routes/admin/trip-detail";
    page: "/trips/:tripId";
  };
  "routes/root/page-layout.tsx": {
    id: "routes/root/page-layout";
    page: "/" | "/travel/:tripId" | "/travel/:tripId/success";
  };
  "routes/root/travel-page.tsx": {
    id: "routes/root/travel-page";
    page: "/";
  };
  "routes/root/travel-detail.tsx": {
    id: "routes/root/travel-detail";
    page: "/travel/:tripId";
  };
  "routes/root/payment-success.tsx": {
    id: "routes/root/payment-success";
    page: "/travel/:tripId/success";
  };
};